executor:
  corePoolSize: 200
  maxPoolSize: 200
  queueCapacity: 1800

scheduler:
  poolSize: 200

agent:
  dryRun: true
  timeout: 500

scripts:
  path: "scripts/"

spring:
  application:
    name: cloud-grpc-server
server:
  port: 0
grpc:
  server:
    port: 3000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}